name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-world Docker image
        run: |
          docker build --tag ghcr.io/tech4germany/inclusify-app:latest -f build/docker-release/Dockerfile .
          docker push ghcr.io/tech4germany/inclusify-app:latest
