name: publish

on: [push]

concurrency:
  group: docker-build-and-publish
  cancel-in-progress: true

jobs:
  publish-inclusify-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_DATE_FN=$(date -u +'%Y-%m-%d_%H%M%S')" >> $GITHUB_ENV

      - name: Build the INCLUSIFY Docker image
        run: |
          docker build . \
            --tag ghcr.io/tech4germany/inclusify-app:${BUILD_DATE_FN} \
            --tag ghcr.io/tech4germany/inclusify-app:latest \
            -f build/docker-release/Dockerfile \
            --build-arg BUILD_DATE=${BUILD_DATE} \
            --build-arg VCS_REVISION=${GITHUB_SHA}
          docker push --all-tags ghcr.io/tech4germany/inclusify-app
