name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build the Inclusify Docker image
        run: |
          docker build --tag ghcr.io/tech4germany/inclusify-app:$(date -u +"%Y-%m-%d_%H%M%S") --tag ghcr.io/tech4germany/inclusify-app:latest -f build/docker-release/Dockerfile .
          docker push --all-tags ghcr.io/tech4germany/inclusify-app
